### ISSUE TITLE
Add optional parameters to claim command (all, outputId, etc.)

### ISSUE THREAD

**Issue by lzpap** [iotaledger/cli-wallet#102]
Currently the `claim` command claims all possibly owned outputs without asking. The user have no way to specify for example to accept incoming transfer of a certain native token, etc.

Add optional parameters to the claim command, for examle to claim a given output or outputs.

It would also be good to add a command to display claimable outputs and show some semantic info about it, this is described in iotaledger/iota-sdk#83

**Comment by thibault-martinez** [comment]
I added an option to claim specific outputs. Were you thinking of anything else for this command @lzpap ?

**Comment by lzpap** [comment]
No, it's enough like this. The improvement would be to display the claimable outputs in a more descriptive way (see iotaledger/iota-sdk#83), but that is a different issue. Thank you @thibault-martinez!
