### ISSUE TITLE
Init the wallet on call without arguments if not already done

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/cli-wallet#110]
## Description

I think it would make sense to also init the wallet if you just call `./wallet` without arguments. Wdyt? Init could also be totally removed. But I don't like that idea...
Or show help if there is nothing initialized yet. But I prefer the first one that.

## Motivation

Many people will just run the binary without arguments at first run.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by Thoralf-M** [comment]
We could check if the db folder exists and run the init method automatically if not

**Comment by thibault-martinez** [comment]
The whole team decided to keep the init command and not call it on `./wallet` without arguments.
