### ISSUE TITLE
After changing nodes with set-node command, coin_type error occurs

### ISSUE THREAD

**Issue by Oli-art** [iotaledger/cli-wallet#124]
## Bug description

After changing nodes with `set-node` command a couple of times, same command fails with wallet error: `missing parameter: coin_type (IOTA: 4218, Shimmer: 4219)`

## Version

Which version of the CLI are you using?

- cli-wallet 1.0.0-alpha.5

## Steps To reproduce the bug

1. `./wallet-linux init -n https://api.alphanet.iotaledger.net` and create password
2. Change node `./wallet-linux set-node https://test-stardust.zentangle.io/`
3. Change node back to the initial one: `./wallet-linux set-node https://api.alphanet.iotaledger.net`

## Expected behaviour

Node should change back to the initial one

## Actual behaviour

Error occurs

## Errors
screenshot of the error:
![image](https://user-images.githubusercontent.com/41125296/177890751-d9fe448e-9eb0-45f4-b16f-2292c42d3e4b.png)
log file:
[archive.log](https://github.com/iotaledger/cli-wallet/files/9067939/archive.log)

**Comment by thibault-martinez** [comment]
Hi @Oli-art, thanks for the report. This should be fixed with https://github.com/iotaledger/cli-wallet/pull/125 now. You can either compile the cli-wallet yourself or wait for the next release that should happen really soon. Please reopen if the issue persists.
