### ISSUE TITLE
Duplicate account names

### ISSUE THREAD

**Issue by laumair** [iotaledger/cli-wallet#13]
## Bug description

CLI wallet allows multiple account creation under a single alias.

## Rust version

Which version of Rust are you running?

- Rust version: 1.48.0

## Version

- Version number, commit, or branch: 4ef9161ec7c8b0ef37e14a3bc4fb4a443dd8e8e0

## Steps To reproduce the bug

1. Run `./wallet new --node http://localhost:14265 --alias Umair`
2. Exit the wallet
3. Run `./wallet new --node http://localhost:14265 --alias Umair` (It will create a new account under alias `Umair`)

## Expected behaviour

The wallet shouldn't allow duplicate account creation under a single alias. It is confusing.
![Screenshot 2020-12-09 at 4 38 25 PM](https://user-images.githubusercontent.com/20437468/101625274-fbb00e00-3a3c-11eb-89c2-66f9d73e68f4.png)

## Actual behaviour

Wallet allows duplicate account creation under a single alias. 

## Errors

N/A

**Comment by lucasfernog** [comment]
Will be available on next release.
