### ISSUE TITLE
Wrong expiration return address while sending native tokens

### ISSUE THREAD

**Issue by lzpap** [iotaledger/cli-wallet#130]
## Bug description

The wallet produces the wrong output when sending native tokens with SDRUC and Expiration.

Example:
I've executed the follwoing command:
```
send-native-token rms1qrut5ajyfrtgjs325kd9chwfwyyy2z3fewy4vgy0vvdtf2pr8prg5u3zwjn 0x0861ba1f25d33a4261c8af09edc325d2e6605b1cb2ea3199256131daa56cc40abc0100000000 1000000
```

My wallet produced the following trasnaction: https://explorer.alphanet.iotaledger.net/alphanet/transaction/0x07c998c7e0fbbfbaaa6d9817d9a9a6b0df3413910f9e5ce32622acfe18a8b213

The first output ([0x07c998c7e0fbbfbaaa6d9817d9a9a6b0df3413910f9e5ce32622acfe18a8b2130000](https://explorer.alphanet.iotaledger.net/alphanet/output/0x07c998c7e0fbbfbaaa6d9817d9a9a6b0df3413910f9e5ce32622acfe18a8b2130000)) of this transaction is the one that defines the SDRUC and Expiration conditions and puts the recipient address the Address Unlock.

Expected behavior:
 - _Address Unlock_ is the recipient: `rms1qrut5ajyfrtgjs325kd9chwfwyyy2z3fewy4vgy0vvdtf2pr8prg5u3zwjn`
 - _SDRUC_ `Return address` is the wallet's own address: `rms1qr8zcma908zz45uzkxjdd8mx2scsmga5cvesm5fzdad2npmszl05g2wtn3l`
 - _Expiration Unlock_ `return address` is the wallet's own address: `rms1qr8zcma908zz45uzkxjdd8mx2scsmga5cvesm5fzdad2npmszl05g2wtn3l`

Actual behavior:
 - _Address Unlock_ is the recipient: `rms1qrut5ajyfrtgjs325kd9chwfwyyy2z3fewy4vgy0vvdtf2pr8prg5u3zwjn`
 - _SDRUC_ `Return address` is the wallet's own address: `rms1qr8zcma908zz45uzkxjdd8mx2scsmga5cvesm5fzdad2npmszl05g2wtn3l`
 - **_Expiration Unlock_ `return address` is the recipient:** `rms1qrut5ajyfrtgjs325kd9chwfwyyy2z3fewy4vgy0vvdtf2pr8prg5u3zwjn`

![image](https://user-images.githubusercontent.com/32927267/179004862-7462f767-5735-4a3c-8c7e-e5c84905d7ad.png)

## Version

Which version of the CLI are you using?

- alpha.7

**Comment by Thoralf-M** [comment]
Fixed in https://github.com/iotaledger/wallet.rs/commit/83b342d6d93bbd541ce54f81a028dc86d14a09a9

**Comment by thibault-martinez** [comment]
@lzpap This should be fixed in alpha.8, please try and close the issue if it's fine 🙏🏻
