### ISSUE TITLE
Display only relevant message & address properties

### ISSUE THREAD

**Issue by laumair** [iotaledger/cli-wallet#14]
## Description

Currently, all message & address properties are displayed on the screen. Many of the properties inside message & address objects serve no purpose to the user. I think it would be better if only relevant properties are displayed to the user. 

## Motivation

Showing all message & address properties take up a lot of space on the screen. 

## Requirements

For messages, imo, the following properties should be displayed:
1. id;
2. version;
3. trunk;
4. branch;
5. timestamp;
6. value;
7. confirmed

For addresses:
1. address;
2. balance;
3. keyIndex;
4. internal

**Comment by lucasfernog** [comment]
I've changed it last week, please reopen if you think something should be changed.
