### ISSUE TITLE
Unable to use wallet because: can't create accounts when the latest account doesn't have message history and balance

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/cli-wallet#73]
Testing the wallet cli.

After some fiddling I am unable to create a new account. I am confronted with the error:

```ERROR: can't create accounts when the latest account doesn't have message history and balance```

but this error message does not tell me how to fix it. What am I supposed to do?

**Comment by Thoralf-M** [comment]
If you get this error then you already have an account and this account needs to get iotas first before you create a new one
This was made so one doesn't create many empty accounts and use only account 40 for example, which would make it much harder to recover if the db is lost
