### ISSUE TITLE
Cannot add new private tangle generated from one-click-tangle as node

### ISSUE THREAD

**Issue by sikhness** [iotaledger/cli-wallet#74]
## Bug description

When trying to create a wallet pointing to a private tangle generated by the one-click-tangle tool, it throws an error and is no longer operational.

## Version

Wallet CLI v0.5.3 (Linux and Windows)

## Hardware specification

What hardware are you using?

- Operating system: Windows 10 / WSL2 (Ubuntu 20.04)
- RAM: 32GB
- Cores: 6

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Run the following command to initialize the wallet `./wallet new --node http://localhost:14265 --alias iota`
2. Set password
3. Error occurs

## Expected behaviour

There should be no error and I should be able to use the wallet as normal.

## Actual behaviour

An error occurs and the program crashes.

## Errors

The following error is thrown:
`Created account 'iota'
Account 'iota' command (h for help): thread 'tokio-runtime-worker' panicked at 'called 'Result::unwrap()' on an 'Err' value: InvalidMqttTopic("addresses/mule1qr3tl65zam2z20gw27ahkfpwjwd6cm93wpvd4m3a75m7a6cfmmnv645czhv/outputs")', /home/runner/.cargo/git/checkouts/wallet.rs-aa79dfe38b7895d2/bd7969c/src/monitor.rs:100:97
                                                                                note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

**Comment by Thoralf-M** [comment]
Seems like your bech32 hrp is `mule`, but we currently only support `(iota|atoi|iot|toi)`

**Comment by sikhness** [comment]
Thank you after changing my node bech32 to `atoi` that error no longer occurs.  Perhaps we can have an enhancement set to include other bech32 for custom addresses?
